# Generated by Django 4.1.7 on 2023-03-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="currency",
        ),
        migrations.AddField(
            model_name="user",
            name="curreny",
            field=models.CharField(
                choices=[("('won', 'Korean Won')", "Won"), ("usd", "Doller")],
                default=1,
                max_length=21,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("('male', 'Male')", "Male"), ("female", "Female")],
                max_length=21,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("('kr', 'Korea')", "Kr"), ("en", "English")], max_length=16
            ),
        ),
    ]
