# Generated by Django 4.1.7 on 2023-03-05 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_alter_room_amenities_alter_room_categroy_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="categroy",
            new_name="category",
        ),
    ]
