# Generated by Django 4.1.7 on 2023-03-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("experiences", "0002_alter_perk_details_alter_perk_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="categroy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
    ]
